"""Hospitality obligation matrix — single source of truth.

Given a Serbian hospitality client's `(legal_form, bookkeeping_system)`
this module returns the set of legally-required forms the agency must
produce for them. Frontend never re-derives — it consumes the matrix via
``GET /api/v1/clients/{id}/obligations``.

Legal basis:
  - Pravilnik o evidenciji prometa (Sl. glasnik RS 99/2015, 44/2018) →
    KEP is universally required for retail (hospitality counts as retail).
  - Pravilnik o poslovnim knjigama (Sl. glasnik RS 140/04) → DPU + PK-1
    are required for prosto knjigovodstvo only.
  - Mišljenje Ministarstva finansija 011-00-761/2018-16 od 23.10.2018 →
    confirms DOOs and preduzetnici on dvojno knjigovodstvo are exempt
    from DPU even when running a hospitality business.

The matrix is encoded as data, not a chain of if-statements, so adding a
future obligation (e.g. a fiscal-receipt evidencija) is a one-liner.
"""

from __future__ import annotations

from typing import Literal

# Form identifiers used by the frontend (the i18n table maps these to
# Serbian display names).
FormKey = Literal[
    "kalkulacija",
    "kep",
    "cenovnik",
    "popis",
    "dpu",
    "pk1",
]

# Per-form status — drives the badge on the "Obavezni obrasci" card.
#   - "shipped"        — currently generated by an existing endpoint
#   - "pre_meeting"    — partially built; column structure pending
#                        validation at the accountant meeting
#   - "post_meeting"   — placeholder, full spec waits for the meeting
#   - "not_applicable" — the obligation matrix says this client doesn't
#                        owe this form
#   - "unclassified"   — the client's legal_form / bookkeeping_system
#                        is unset; the card shows a "set legal form"
#                        prompt instead of a status badge
FormStatus = Literal[
    "shipped",
    "pre_meeting",
    "post_meeting",
    "not_applicable",
    "unclassified",
]

# What's actually wired up today. Kept in one place so the obligation
# card is honest about which forms are real vs placeholder.
# kalkulacija + dpu already exist as endpoints under /api/v1/reports/ but
# their column structures are simplified pre-meeting drafts; column-level
# validation against the legally-prescribed 13-col KL and 9-col DPU forms
# is pending the accountant meeting.
_BUILD_STATUS: dict[FormKey, FormStatus] = {
    "kalkulacija": "pre_meeting",
    "dpu": "pre_meeting",
    "kep": "post_meeting",
    "cenovnik": "post_meeting",
    "popis": "post_meeting",
    "pk1": "post_meeting",
}

# Forms that apply universally to any classified hospitality client.
# DPU and PK-1 are dvojno-exempt and added separately below.
_HOSPITALITY_BASE: frozenset[FormKey] = frozenset({"kalkulacija", "kep", "cenovnik", "popis"})

# Forms that only apply when the client keeps prosto knjigovodstvo.
# Source: Pravilnik o poslovnim knjigama 140/04 + Mišljenje MF
# 011-00-761/2018-16.
_PROSTO_ONLY: frozenset[FormKey] = frozenset({"dpu", "pk1"})


def required_forms(
    legal_form: str | None,
    bookkeeping_system: str | None,
) -> dict[FormKey, FormStatus]:
    """Return the obligation matrix for one client.

    Args:
        legal_form: Client's legal form. One of "DOO", "preduzetnik",
            "paušalac", "drugo", or None (unclassified).
        bookkeeping_system: Client's bookkeeping system. "dvojno",
            "prosto", or None.

    Returns:
        Dict keyed by FormKey. Every known FormKey is present in the
        result so the frontend can render a complete table without
        further enumeration; the value is either the actual build
        status when the form is owed, "not_applicable" when the
        client's profile doesn't owe it, or "unclassified" when we
        cannot decide yet.
    """
    # No classification → ask the agency to classify.
    if legal_form is None:
        return {key: "unclassified" for key in _BUILD_STATUS}

    # Paušalci are out of Saldora's scope (see Section 4.17).
    if legal_form == "paušalac":
        return {key: "not_applicable" for key in _BUILD_STATUS}

    # DOO is implied to be dvojno by Zakon o računovodstvu — we don't
    # require the agency to also set bookkeeping_system for DOOs.
    if legal_form == "DOO":
        effective_bookkeeping = "dvojno"
    else:
        effective_bookkeeping = bookkeeping_system

    # Preduzetnik / drugo without explicit bookkeeping is still
    # ambiguous on DPU + PK-1; surface the base obligations and leave
    # the prosto-only ones as unclassified so the agency knows to fill
    # in the second field.
    if effective_bookkeeping is None:
        result: dict[FormKey, FormStatus] = {}
        for key in _BUILD_STATUS:
            if key in _HOSPITALITY_BASE:
                result[key] = _BUILD_STATUS[key]
            else:
                result[key] = "unclassified"
        return result

    # Fully classified — apply the matrix.
    obligations: set[FormKey] = set(_HOSPITALITY_BASE)
    if effective_bookkeeping == "prosto":
        obligations |= _PROSTO_ONLY

    return {
        key: (_BUILD_STATUS[key] if key in obligations else "not_applicable")
        for key in _BUILD_STATUS
    }
