"""Add KPO ledger (Knjiga o ostvarenom prometu) for paušalci.

KPO entries are the immutable legal record of revenue generated by a
paušalac. One entry per issued invoice (auto-populated) plus optional
manual entries for back-filling pre-Saldora history, plus storno
(corrective) entries linked to the original they reverse.

Revision ID: 0016
Revises: 0015
Create Date: 2026-04-20
"""

import sqlalchemy as sa

from alembic import op

revision = "0016"
down_revision = "0015"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "kpo_entries",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "client_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clients.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "organization_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("organizations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "invoice_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("invoices.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "storno_of_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("kpo_entries.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("entry_number", sa.String(length=20), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("customer_pib", sa.String(length=20), nullable=True),
        sa.Column(
            "amount",
            sa.Numeric(15, 2),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="RSD"),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_cancelled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.UniqueConstraint(
            "client_id", "year", "entry_number", name="uq_kpo_entry_client_year_number"
        ),
    )
    op.create_index("ix_kpo_entries_client_id", "kpo_entries", ["client_id"])
    op.create_index("ix_kpo_entries_org_id", "kpo_entries", ["organization_id"])
    op.create_index("ix_kpo_entries_invoice_id", "kpo_entries", ["invoice_id"])
    op.create_index(
        "ix_kpo_entries_client_year",
        "kpo_entries",
        ["client_id", "year"],
    )


def downgrade() -> None:
    op.drop_index("ix_kpo_entries_client_year", table_name="kpo_entries")
    op.drop_index("ix_kpo_entries_invoice_id", table_name="kpo_entries")
    op.drop_index("ix_kpo_entries_org_id", table_name="kpo_entries")
    op.drop_index("ix_kpo_entries_client_id", table_name="kpo_entries")
    op.drop_table("kpo_entries")
