"""create initial tables

Revision ID: 98666451fc88
Revises:
Create Date: 2026-02-17 09:18:11.988028

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "98666451fc88"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
