"""add document_hash column to invoices

Revision ID: e94adbad28e1
Revises: 3d0058768c77
Create Date: 2026-02-25 18:55:11.965063

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e94adbad28e1"
down_revision: str | Sequence[str] | None = "3d0058768c77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("document_hash", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_invoices_document_hash"), "invoices", ["document_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoices_document_hash"), table_name="invoices")
    op.drop_column("invoices", "document_hash")
    # ### end Alembic commands ###
